In [1]:
import numpy as np

### <font color='blue'>ソフトマックス関数</font>

In [2]:
a = np.array([0.3, 2.9, 4.0])

In [3]:
exp_a = np.exp(a)

In [4]:
exp_a

array([  1.34985881,  18.17414537,  54.59815003])

In [5]:
sum_exp_a = np.sum(exp_a)

In [6]:
sum_exp_a

74.122154210163302

In [7]:
y = exp_a / sum_exp_a

In [8]:
y

array([ 0.01821127,  0.24519181,  0.73659691])

### <font color='blue'>ソフトマックス関数を実装する際の注意点</font>

ソフトマックス関数を実装する上での注意点として<br>
オーバーフローの問題が存在する。<br>
指数関数の計算を行うときに、指数関数が大きくなりすぎた場合、値を計算することができなくなる。<br>

In [9]:
a = np.array([1010, 1000, 990])

In [10]:
np.exp(a) / np.sum(np.exp(a))

/Users/Takanori/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: overflow encountered in exp
  """Entry point for launching an IPython kernel.
/Users/Takanori/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([ nan,  nan,  nan])

In [11]:
c = np.max(a)

In [12]:
a - c

array([  0, -10, -20])

In [13]:
np.exp(a - c) / np.sum(np.exp(a - c))

array([  9.99954600e-01,   4.53978686e-05,   2.06106005e-09])

上記のように普通に計算していたらnanであるが、最大値を引くことによって正しく計算可能である。<br>

In [14]:
# ソフトマックス関数
def softmax(a):
    c = np.max(a)
    exp_a = np.exp(a-c)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    return y

In [16]:
a = np.array([0.3, 2.9, 4.0])
y = softmax(a)

In [17]:
np.sum(y)

1.0